name: Deploy PRODUCTION environment

on: push

permissions:
  contents: read
  pull-requests: write

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    steps:
    

      - name: Test env variables to other steps
        run: |
          echo "Something"
          