name: Explorer App E2E Tests

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        # containers: [1, 2] # Uses 2 parallel instances
        containers: [1] # Uses 2 parallel instances
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
          # FOR PULL REQUEST branch_name=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/refs\/heads\///')
          # FOR PUSH TEST - branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
      - name: Extract branch specific url based on branch name and Jira ticket pattern (DDEV-XXXX)
        run: |
          branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          jira_ticket=$(echo $branch_name | grep -o 'DDEV-[0-9]\+')
          echo "Branch name: $branch_name"
          echo "JIRA ticket: $jira_ticket"
          branch_specific_link="https://cce-${jira_ticket}-staging.vercel.app"
          echo "Branch specific link: $branch_specific_link"
          echo "{branch_specific_link}={$branch_specific_link}" >> $GITHUB_ENV
        env:
          branch_specific_link: $branch_specific_link
          
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_APP_BASE_URL: ${{ github.ref | sed 's/refs\/heads\///' | grep -o 'DDEV-[0-9]\+' }}

          
