name: Explorer App E2E Tests

on: 
  pull_request:
    types: [synchronize, opened]

permissions:
  contents: read
  pull-requests: write

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        # containers: [1, 2] # Uses 2 parallel instances
        containers: [1] # Uses 2 parallel instances
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
          # FOR PULL REQUEST branch_name=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/refs\/heads\///')
          # FOR PUSH TEST - branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
      - name: Extract branch specific url based on branch name and Jira ticket pattern (DDEV-XXXX)
        run: |
          branch_to_name=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/refs\/heads\///')
          echo "branch_to_name: $branch_to_name"
          
          branch_from_name=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/refs\/heads\///')
          echo "branch_from_name: $branch_from_name"
          
          jira_ticket=$(echo $branch_from_name | grep -o 'DDEV-[0-9]\+')
          echo "JIRA ticket: $jira_ticket"
          
          test_link_production="https://cce-${jira_ticket}-production.vercel.app"
          echo "test_link_production=$test_link_production" >> $GITHUB_ENV
          
          test_link_staging="https://cce-${jira_ticket}-staging.vercel.app"
          echo "test_link_staging=$test_link_staging" >> $GITHUB_ENV

      - name: Test env variables to other steps
        run: |
          echo "${{ env.test_link_production }}"
          echo "${{ env.test_link_staging }}"

      - name: Cypress run STAGING ENV
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_APP_BASE_URL: ${{ env.test_link_staging }}

      - name: Cypress run PRODUCTION ENV
        uses: cypress-io/github-action@v4
        if: ${{ github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'DDEV-477' }}
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_APP_BASE_URL: ${{ env.test_link_production }}


          
